
package proyecto.licencias.de.funcionamiento;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author Daniel
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jB_gestor = new javax.swing.JButton();
        jB_registrar = new javax.swing.JButton();
        jB_busqueda = new javax.swing.JButton();
        jB_reportes = new javax.swing.JButton();
        jB_datos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 102, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(47, 47, 77));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTOR DE LICENCIAS DE FUNCIONAMIENTO");

        jB_gestor.setBackground(new java.awt.Color(98, 105, 112));
        jB_gestor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jB_gestor.setForeground(new java.awt.Color(255, 255, 255));
        jB_gestor.setText("Gestor de Archivos");
        jB_gestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_gestorActionPerformed(evt);
            }
        });

        jB_registrar.setBackground(new java.awt.Color(98, 105, 112));
        jB_registrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jB_registrar.setForeground(new java.awt.Color(255, 255, 255));
        jB_registrar.setText("Registro de Licencia");
        jB_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_registrarActionPerformed(evt);
            }
        });

        jB_busqueda.setBackground(new java.awt.Color(98, 105, 112));
        jB_busqueda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jB_busqueda.setForeground(new java.awt.Color(255, 255, 255));
        jB_busqueda.setText("Busqueda de Licencia");
        jB_busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_busquedaActionPerformed(evt);
            }
        });

        jB_reportes.setBackground(new java.awt.Color(98, 105, 112));
        jB_reportes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jB_reportes.setForeground(new java.awt.Color(255, 255, 255));
        jB_reportes.setText("Generar Reporte");
        jB_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_reportesActionPerformed(evt);
            }
        });

        jB_datos.setBackground(new java.awt.Color(98, 105, 112));
        jB_datos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jB_datos.setForeground(new java.awt.Color(255, 255, 255));
        jB_datos.setText("Datos");
        jB_datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_datosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jB_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_gestor, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(188, 188, 188))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(82, 82, 82)
                .addComponent(jB_gestor)
                .addGap(18, 18, 18)
                .addComponent(jB_registrar)
                .addGap(18, 18, 18)
                .addComponent(jB_busqueda)
                .addGap(18, 18, 18)
                .addComponent(jB_reportes)
                .addGap(18, 18, 18)
                .addComponent(jB_datos)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_registrarActionPerformed
        VentanaRegistroLi ventana = new VentanaRegistroLi();
        ventana.setVisible(true);
    }//GEN-LAST:event_jB_registrarActionPerformed

    private void jB_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_busquedaActionPerformed
        VentanaBusqueda ventana = new VentanaBusqueda();
        ventana.setVisible(true);
    }//GEN-LAST:event_jB_busquedaActionPerformed

    private void jB_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_reportesActionPerformed
        VentanaReporte ventana = new VentanaReporte();
        ventana.setVisible(true);
    }//GEN-LAST:event_jB_reportesActionPerformed

    private void jB_gestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_gestorActionPerformed
        VentanaGestor ventana = new VentanaGestor();
        ventana.setVisible(true);
        
    }//GEN-LAST:event_jB_gestorActionPerformed

    private void jB_datosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_datosActionPerformed
        TablaMostrarDatos tabla = new TablaMostrarDatos();
        tabla.llenarTabla();
        tabla.setVisible(true);
    }//GEN-LAST:event_jB_datosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_busqueda;
    private javax.swing.JButton jB_datos;
    private javax.swing.JButton jB_gestor;
    private javax.swing.JButton jB_registrar;
    private javax.swing.JButton jB_reportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
